### PR TITLE
Add git to pylint and cppcheck image to allow use with gitlab.

### PR DESCRIPTION
**Pull request by afics**

### CODE REVIEW

**Comment by blatyo** [comment]
Instead of adding `git` there, can you instead change the `FROM` to `buildpack-deps:jessie-scm`. It allows better reuse of layers, between these and the other images. Thanks!

BTW, how did you find this project?

**Comment by afics** [comment]
Ah, I didn't know about `buildpack-deps:jessie-scm`. I searched docker hubs for `cppcheck`.

**Comment by blatyo** [comment]
I think you might have reverted the wrong commit. You reverted the version bump on master. If you don't mind, could you create a new branch with just the `FROM` change in a single commit? Thanks

**Comment by afics** [comment]
Whoops, sorry, will do.

**Pull request closed without merging**
